import {
  Award,
  BarChart3,
  Bell,
  BookOpen,
  CalendarCheck,
  CalendarClock,
  CircleDot,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  Home,
  Layers3,
  Medal,
  MapPinned,
  TrendingUp,
  ScrollText,
  Settings,
  Target,
  User,
  UserRoundCheck,
  Users,
  Wrench,
} from 'lucide-react';

export const appNavigation = [
  {
    id: 'dashboard',
    labelKey: 'layout:navigation.dashboard',
    icon: Home,
    to: '/dashboard',
  },
  {
    id: 'worship',
    labelKey: 'layout:navigation.worship',
    icon: CalendarCheck,
    items: [
      {
        id: 'today-worship',
        labelKey: 'layout:navigation.todayWorship',
        icon: ClipboardList,
        to: '/tracking',
        permissions: ['tracking.manage_self'],
      },
      {
        id: 'worship-library',
        labelKey: 'layout:navigation.worshipLibrary',
        icon: BookOpen,
        to: '/worship',
        permissions: ['worship.items.manage'],
      },
      {
        id: 'missions',
        labelKey: 'layout:navigation.missions',
        icon: Target,
        to: '/missions',
        permissions: ['missions.view_own', 'missions.assign', 'missions.manage_region', 'missions.manage_all'],
        permissionMode: 'any',
      },
    ],
  },
  {
    id: 'progress',
    labelKey: 'layout:navigation.progress',
    icon: BarChart3,
    items: [
      {
        id: 'reports',
        labelKey: 'layout:navigation.reports',
        icon: ScrollText,
        to: '/reports',
        permissions: ['reports.view_own', 'reports.view_assigned', 'reports.view_region', 'reports.view_all'],
        permissionMode: 'any',
      },
      {
        id: 'mentor-dashboard',
        labelKey: 'layout:navigation.mentorDashboard',
        icon: Users,
        to: '/mentor/dashboard',
        permissions: ['reviews.manage_assigned', 'reviews.manage_region', 'reviews.manage_all'],
        permissionMode: 'any',
      },
      {
        id: 'mentor-reviews',
        labelKey: 'layout:navigation.mentorReviews',
        icon: ClipboardCheck,
        to: '/mentor/reviews',
        permissions: ['reviews.manage_assigned', 'reviews.manage_region', 'reviews.manage_all'],
        permissionMode: 'any',
      },
      {
        id: 'promotions',
        labelKey: 'layout:navigation.promotions',
        icon: TrendingUp,
        to: '/promotions',
        permissions: ['levels.promote'],
      },
      {
        id: 'my-reviews',
        labelKey: 'layout:navigation.myReviews',
        icon: ClipboardCheck,
        to: '/reviews',
        permissions: ['reviews.view_own'],
      },
      {
        id: 'achievements',
        labelKey: 'layout:navigation.achievements',
        icon: Award,
        to: '/achievements',
        permissions: ['achievements.view', 'achievements.manage'],
        permissionMode: 'any',
      },
      {
        id: 'badges',
        labelKey: 'layout:navigation.badges',
        icon: Medal,
        to: '/badges',
        permissions: ['badges.view', 'badges.manage'],
        permissionMode: 'any',
      },
    ],
  },
  {
    id: 'tools',
    labelKey: 'layout:navigation.tools',
    icon: Wrench,
    items: [
      {
        id: 'tasbih',
        labelKey: 'layout:navigation.tasbih',
        icon: CircleDot,
        to: '/tools/tasbih',
      },
      {
        id: 'prayer-progress',
        labelKey: 'layout:navigation.prayerProgress',
        icon: Clock3,
        to: '/tools/prayer-progress',
      },
      {
        id: 'ramadan-countdown',
        labelKey: 'layout:navigation.ramadanCountdown',
        icon: CalendarClock,
        to: '/tools/ramadan-countdown',
      },
    ],
  },
  {
    id: 'admin',
    labelKey: 'layout:navigation.admin',
    icon: UserRoundCheck,
    permissions: ['regions.manage', 'users.manage_all', 'users.manage_region', 'users.assign', 'users.transfer_mentor', 'worship.items.manage', 'levels.manage', 'levels.promote'],
    permissionMode: 'any',
    items: [
      {
        id: 'regions',
        labelKey: 'layout:navigation.regions',
        icon: MapPinned,
        to: '/admin/regions',
        permissions: ['regions.manage'],
      },
      {
        id: 'users',
        labelKey: 'layout:navigation.users',
        icon: Users,
        to: '/admin/users',
        permissions: ['users.manage_all', 'users.manage_region'],
        permissionMode: 'any',
      },
      {
        id: 'mentor-assignments',
        labelKey: 'layout:navigation.mentorAssignments',
        icon: UserRoundCheck,
        to: '/admin/mentor-assignments',
        permissions: ['users.manage_all', 'users.manage_region', 'users.assign', 'users.transfer_mentor'],
        permissionMode: 'any',
      },
      {
        id: 'worship-curriculum',
        labelKey: 'layout:navigation.worshipSchedule',
        icon: BookOpen,
        to: '/admin/worship-curriculum',
        permissions: ['worship.items.manage'],
      },
      {
        id: 'worship-levels',
        labelKey: 'layout:navigation.worshipLevels',
        icon: Layers3,
        to: '/admin/worship-levels',
        permissions: ['levels.manage', 'levels.promote'],
        permissionMode: 'any',
      },
    ],
  },
  {
    id: 'account',
    labelKey: 'layout:navigation.account',
    icon: User,
    items: [
      {
        id: 'notifications',
        labelKey: 'layout:navigation.notifications',
        icon: Bell,
        to: '/notifications',
        permissions: ['notifications.view_own', 'notifications.view_assigned', 'notifications.manage_region', 'notifications.manage_all'],
        permissionMode: 'any',
      },
      {
        id: 'profile',
        labelKey: 'layout:navigation.profile',
        icon: User,
        to: '/profile',
      },
      {
        id: 'settings',
        labelKey: 'layout:navigation.settings',
        icon: Settings,
        to: '/settings',
      },
    ],
  },
];

export function flattenNavigation(items = appNavigation) {
  return items.flatMap((item) => (item.items ? flattenNavigation(item.items) : [item]));
}
