export const ONBOARDING_STATUS = {
  PENDING_SETUP: 'PENDING_SETUP',
  ACTIVE: 'ACTIVE',
};

export const MENTOR_ASSIGNMENT_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
};

export const TODAY_WORSHIP_READINESS = {
  READY: 'READY',
  ONBOARDING_INCOMPLETE: 'ONBOARDING_INCOMPLETE',
  NO_ACTIVE_WORSHIP_LEVEL: 'NO_ACTIVE_WORSHIP_LEVEL',
  NO_LEVEL_REQUIREMENTS: 'NO_LEVEL_REQUIREMENTS',
  NO_WORSHIP_ITEMS_CONFIGURED: 'NO_WORSHIP_ITEMS_CONFIGURED',
};

export const PENDING_SETUP_REGION_NAME = 'Pending Setup';
