export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  REGION_ADMIN: 'REGION_ADMIN',
  MENTOR: 'MENTOR',
  USER: 'USER',
};

export const ROLE_DEFINITIONS = [
  {
    code: ROLES.SUPER_ADMIN,
    name: 'Super Admin',
    description: 'Full system access.',
  },
  {
    code: ROLES.REGION_ADMIN,
    name: 'Region Admin',
    description: 'Administrative access scoped to one region.',
  },
  {
    code: ROLES.MENTOR,
    name: 'Mentor',
    description: 'Access to assigned users and mentorship workflows.',
  },
  {
    code: ROLES.USER,
    name: 'User',
    description: 'Access to own tracking, journey, reports, and profile.',
  },
];

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  USERS_MANAGE_ALL: 'users.manage_all',
  USERS_MANAGE_REGION: 'users.manage_region',
  USERS_VIEW_ASSIGNED: 'users.view_assigned',
  USERS_VIEW_SELF: 'users.view_self',
  USERS_CREATE: 'users.create',
  USERS_ASSIGN: 'users.assign',
  USERS_TRANSFER_REGION: 'users.transfer_region',
  USERS_TRANSFER_MENTOR: 'users.transfer_mentor',
  REGIONS_MANAGE: 'regions.manage',
  REGIONS_VIEW_OWN: 'regions.view_own',
  MENTORS_MANAGE: 'mentors.manage',
  LEVELS_MANAGE: 'levels.manage',
  LEVELS_PROMOTE: 'levels.promote',
  LEVELS_VIEW: 'levels.view',
  WORSHIP_CATEGORIES_MANAGE: 'worship.categories.manage',
  WORSHIP_ITEMS_MANAGE: 'worship.items.manage',
  WORSHIP_VIEW: 'worship.view',
  TRACKING_MANAGE_ALL: 'tracking.manage_all',
  TRACKING_MANAGE_REGION: 'tracking.manage_region',
  TRACKING_REVIEW_ASSIGNED: 'tracking.review_assigned',
  TRACKING_MANAGE_SELF: 'tracking.manage_self',
  REVIEWS_MANAGE_ALL: 'reviews.manage_all',
  REVIEWS_MANAGE_REGION: 'reviews.manage_region',
  REVIEWS_MANAGE_ASSIGNED: 'reviews.manage_assigned',
  REVIEWS_VIEW_OWN: 'reviews.view_own',
  MISSIONS_MANAGE_ALL: 'missions.manage_all',
  MISSIONS_MANAGE_REGION: 'missions.manage_region',
  MISSIONS_ASSIGN: 'missions.assign',
  MISSIONS_VIEW_OWN: 'missions.view_own',
  REPORTS_VIEW_ALL: 'reports.view_all',
  REPORTS_VIEW_REGION: 'reports.view_region',
  REPORTS_VIEW_ASSIGNED: 'reports.view_assigned',
  REPORTS_VIEW_OWN: 'reports.view_own',
  NOTIFICATIONS_MANAGE_ALL: 'notifications.manage_all',
  NOTIFICATIONS_MANAGE_REGION: 'notifications.manage_region',
  NOTIFICATIONS_VIEW_ASSIGNED: 'notifications.view_assigned',
  NOTIFICATIONS_VIEW_OWN: 'notifications.view_own',
  AUDIT_LOGS_VIEW: 'audit_logs.view',
  SETTINGS_MANAGE_SYSTEM: 'settings.manage_system',
  SETTINGS_MANAGE_REGION: 'settings.manage_region',
  SETTINGS_MANAGE_PROFILE: 'settings.manage_profile',
  PROFILE_UPDATE_OWN: 'profile.update_own',
  BADGES_MANAGE: 'badges.manage',
  BADGES_VIEW: 'badges.view',
  ACHIEVEMENTS_MANAGE: 'achievements.manage',
  ACHIEVEMENTS_VIEW: 'achievements.view',
  ENCOURAGEMENT_SEND: 'encouragement.send',
  MENTOR_NOTES_MANAGE: 'mentor_notes.manage',
  WEEK_REOPEN: 'weeks.reopen',
  REGION_ADMINS_ASSIGN: 'region_admins.assign',
};

export const PERMISSION_REGISTRY = [
  { code: PERMISSIONS.DASHBOARD_VIEW, name: 'View dashboard', module: 'dashboard' },
  { code: PERMISSIONS.USERS_MANAGE_ALL, name: 'Manage all users', module: 'users' },
  { code: PERMISSIONS.USERS_MANAGE_REGION, name: 'Manage region users', module: 'users' },
  { code: PERMISSIONS.USERS_VIEW_ASSIGNED, name: 'View assigned users', module: 'users' },
  { code: PERMISSIONS.USERS_VIEW_SELF, name: 'View own user profile', module: 'users' },
  { code: PERMISSIONS.USERS_CREATE, name: 'Create users', module: 'users' },
  { code: PERMISSIONS.USERS_ASSIGN, name: 'Assign users to mentors', module: 'users' },
  { code: PERMISSIONS.USERS_TRANSFER_REGION, name: 'Transfer users between regions', module: 'users' },
  { code: PERMISSIONS.USERS_TRANSFER_MENTOR, name: 'Transfer users between mentors', module: 'users' },
  { code: PERMISSIONS.REGIONS_MANAGE, name: 'Manage regions', module: 'regions' },
  { code: PERMISSIONS.REGIONS_VIEW_OWN, name: 'View own region', module: 'regions' },
  { code: PERMISSIONS.MENTORS_MANAGE, name: 'Manage mentors', module: 'mentors' },
  { code: PERMISSIONS.LEVELS_MANAGE, name: 'Manage levels', module: 'levels' },
  { code: PERMISSIONS.LEVELS_PROMOTE, name: 'Approve worship level promotions', module: 'levels' },
  { code: PERMISSIONS.LEVELS_VIEW, name: 'View levels', module: 'levels' },
  { code: PERMISSIONS.WORSHIP_CATEGORIES_MANAGE, name: 'Manage worship categories', module: 'worship' },
  { code: PERMISSIONS.WORSHIP_ITEMS_MANAGE, name: 'Manage worship items', module: 'worship' },
  { code: PERMISSIONS.WORSHIP_VIEW, name: 'View worship items', module: 'worship' },
  { code: PERMISSIONS.TRACKING_MANAGE_ALL, name: 'Manage all tracking', module: 'tracking' },
  { code: PERMISSIONS.TRACKING_MANAGE_REGION, name: 'Manage region tracking', module: 'tracking' },
  { code: PERMISSIONS.TRACKING_REVIEW_ASSIGNED, name: 'Review assigned tracking', module: 'tracking' },
  { code: PERMISSIONS.TRACKING_MANAGE_SELF, name: 'Manage own tracking', module: 'tracking' },
  { code: PERMISSIONS.REVIEWS_MANAGE_ALL, name: 'Manage all reviews', module: 'reviews' },
  { code: PERMISSIONS.REVIEWS_MANAGE_REGION, name: 'Manage region reviews', module: 'reviews' },
  { code: PERMISSIONS.REVIEWS_MANAGE_ASSIGNED, name: 'Manage assigned reviews', module: 'reviews' },
  { code: PERMISSIONS.REVIEWS_VIEW_OWN, name: 'View own reviews', module: 'reviews' },
  { code: PERMISSIONS.MISSIONS_MANAGE_ALL, name: 'Manage all missions', module: 'missions' },
  { code: PERMISSIONS.MISSIONS_MANAGE_REGION, name: 'Manage region missions', module: 'missions' },
  { code: PERMISSIONS.MISSIONS_ASSIGN, name: 'Assign missions', module: 'missions' },
  { code: PERMISSIONS.MISSIONS_VIEW_OWN, name: 'View own missions', module: 'missions' },
  { code: PERMISSIONS.REPORTS_VIEW_ALL, name: 'View all reports', module: 'reports' },
  { code: PERMISSIONS.REPORTS_VIEW_REGION, name: 'View region reports', module: 'reports' },
  { code: PERMISSIONS.REPORTS_VIEW_ASSIGNED, name: 'View assigned user reports', module: 'reports' },
  { code: PERMISSIONS.REPORTS_VIEW_OWN, name: 'View own reports', module: 'reports' },
  { code: PERMISSIONS.NOTIFICATIONS_MANAGE_ALL, name: 'Manage all notifications', module: 'notifications' },
  { code: PERMISSIONS.NOTIFICATIONS_MANAGE_REGION, name: 'Manage region notifications', module: 'notifications' },
  { code: PERMISSIONS.NOTIFICATIONS_VIEW_ASSIGNED, name: 'View assigned notifications', module: 'notifications' },
  { code: PERMISSIONS.NOTIFICATIONS_VIEW_OWN, name: 'View own notifications', module: 'notifications' },
  { code: PERMISSIONS.AUDIT_LOGS_VIEW, name: 'View audit logs', module: 'audit_logs' },
  { code: PERMISSIONS.SETTINGS_MANAGE_SYSTEM, name: 'Manage system settings', module: 'settings' },
  { code: PERMISSIONS.SETTINGS_MANAGE_REGION, name: 'Manage region settings', module: 'settings' },
  { code: PERMISSIONS.SETTINGS_MANAGE_PROFILE, name: 'Manage profile settings', module: 'settings' },
  { code: PERMISSIONS.PROFILE_UPDATE_OWN, name: 'Update own profile', module: 'profile' },
  { code: PERMISSIONS.BADGES_MANAGE, name: 'Manage badges', module: 'badges' },
  { code: PERMISSIONS.BADGES_VIEW, name: 'View badges', module: 'badges' },
  { code: PERMISSIONS.ACHIEVEMENTS_MANAGE, name: 'Manage achievements', module: 'achievements' },
  { code: PERMISSIONS.ACHIEVEMENTS_VIEW, name: 'View achievements', module: 'achievements' },
  { code: PERMISSIONS.ENCOURAGEMENT_SEND, name: 'Send encouragement', module: 'encouragement' },
  { code: PERMISSIONS.MENTOR_NOTES_MANAGE, name: 'Manage mentor notes', module: 'mentor_notes' },
  { code: PERMISSIONS.WEEK_REOPEN, name: 'Reopen closed weeks', module: 'weeks' },
  { code: PERMISSIONS.REGION_ADMINS_ASSIGN, name: 'Assign region admins', module: 'region_admins' },
];

const SUPER_ADMIN_PERMISSIONS = Object.values(PERMISSIONS);

const REGION_ADMIN_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.USERS_MANAGE_REGION,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_ASSIGN,
  PERMISSIONS.USERS_TRANSFER_MENTOR,
  PERMISSIONS.REGIONS_VIEW_OWN,
  PERMISSIONS.MENTORS_MANAGE,
  PERMISSIONS.LEVELS_VIEW,
  PERMISSIONS.LEVELS_PROMOTE,
  PERMISSIONS.WORSHIP_VIEW,
  PERMISSIONS.TRACKING_MANAGE_REGION,
  PERMISSIONS.REVIEWS_MANAGE_REGION,
  PERMISSIONS.MISSIONS_MANAGE_REGION,
  PERMISSIONS.REPORTS_VIEW_REGION,
  PERMISSIONS.NOTIFICATIONS_MANAGE_REGION,
  PERMISSIONS.SETTINGS_MANAGE_REGION,
  PERMISSIONS.BADGES_VIEW,
  PERMISSIONS.ACHIEVEMENTS_VIEW,
];

const MENTOR_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.USERS_VIEW_ASSIGNED,
  PERMISSIONS.LEVELS_VIEW,
  PERMISSIONS.LEVELS_PROMOTE,
  PERMISSIONS.WORSHIP_VIEW,
  PERMISSIONS.TRACKING_REVIEW_ASSIGNED,
  PERMISSIONS.REVIEWS_MANAGE_ASSIGNED,
  PERMISSIONS.MISSIONS_ASSIGN,
  PERMISSIONS.REPORTS_VIEW_ASSIGNED,
  PERMISSIONS.NOTIFICATIONS_VIEW_ASSIGNED,
  PERMISSIONS.BADGES_VIEW,
  PERMISSIONS.ACHIEVEMENTS_VIEW,
  PERMISSIONS.ENCOURAGEMENT_SEND,
  PERMISSIONS.MENTOR_NOTES_MANAGE,
];

const USER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.USERS_VIEW_SELF,
  PERMISSIONS.LEVELS_VIEW,
  PERMISSIONS.WORSHIP_VIEW,
  PERMISSIONS.TRACKING_MANAGE_SELF,
  PERMISSIONS.REVIEWS_VIEW_OWN,
  PERMISSIONS.MISSIONS_VIEW_OWN,
  PERMISSIONS.REPORTS_VIEW_OWN,
  PERMISSIONS.NOTIFICATIONS_VIEW_OWN,
  PERMISSIONS.SETTINGS_MANAGE_PROFILE,
  PERMISSIONS.PROFILE_UPDATE_OWN,
  PERMISSIONS.BADGES_VIEW,
  PERMISSIONS.ACHIEVEMENTS_VIEW,
];

export const ROLE_PERMISSION_MAP = {
  [ROLES.SUPER_ADMIN]: SUPER_ADMIN_PERMISSIONS,
  [ROLES.REGION_ADMIN]: REGION_ADMIN_PERMISSIONS,
  [ROLES.MENTOR]: MENTOR_PERMISSIONS,
  [ROLES.USER]: USER_PERMISSIONS,
};
